name: SSH Git Pull

on:
  push:
    branches:
      - dev # Ejecutar cuando haya un push en la rama 'dev2'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout del código
        uses: actions/checkout@v3

      # 2. Configurar la clave SSH
      - name: Configurar la clave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # 3. Agregar el servidor al archivo de hosts conocidos
      - name: Configurar Host SSH
        run: |
          ssh-keyscan -H ${{ secrets.SSH_HOST_FRONT }} >> ~/.ssh/known_hosts

      # 4. Conectarse al servidor, cambiar de directorio y hacer git pull
      - name: Conectar al servidor y desplegar Frontend
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST_FRONT }} << 'EOF'
            cd /home/${SSH_USERNAME}

            if [ ! -d "./Frontend" ]; then
              git clone https://github.com/Deliverar-Datos/Frontend.git
            fi

            cd ./Frontend/frontend-bi
            git pull

            export NVM_DIR="\$HOME/.nvm"
            source "\$NVM_DIR/nvm.sh"
            nvm use 22

            npm install
            npm run build

            sudo cp -r ./build/* /var/www/mi-app-react/
            ls -la /var/www/mi-app-react/

            echo "Se copió la aplicación"
            sudo systemctl restart nginx.service
            echo "Se reinició el servicio de Nginx"
          EOF
